### PR TITLE
Fix issue#170 Player'naturalSize doesn't match the actual video size

### PR DESCRIPTION
**Pull request by 131e55**
Hello😸

I fixed Issue #170 by reference to https://stackoverflow.com/questions/10433774/avurlasset-getting-video-size

Please review🙇

### CODE REVIEW

**Comment by piemonte** [comment]
thanks for the contributions @131e55 – you're awesome! ✌️

**Comment by piemonte** [comment]
@131e55 hey keisuke – appreciate the contributions, i've invited you to be a collaborator for the project.

**Comment by 131e55** [comment]
@piemonte Sorry for the late reply:bow:

Thank you so much for your invitation:exclamation:
However, I can't spend much time for the project so I want to contribute as before.

Thank you again.

**Comment by piemonte** [comment]
that's ok! ✌️

**Pull request merged**
