### PR TITLE
Fix Carthage Installation

### LINKED ISSUE #144: Unable to install with Carthage
Cartfile:
```
github "piemonte/Player" ~> 0.5.0
```

Carthage command:
```
carthage update --platform iOS --cache-builds
```

Output:
```
*** Fetching Player
*** Checking out Player at "0.5.1"
*** No cache found for Player, building with all downstream dependencies
*** Skipped building Player due to the error:
Dependency "Player" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/piemonte/Player/issues/new
```

If I try running it without the `--platform iOS`, I get the same issue reported in #33:
```
*** Skipped building Player due to the error:
Dependency "Player" has no shared framework schemes
```

I cloned Player locally and tried to debug. I think the easiest path to fixing this will be debugging why the following command fails, which is a pretty standard command line build and indeed what Carthage is using to try to build it with `carthage build --no-skip-current`:
```
/usr/bin/xcrun xcodebuild -workspace /Users/eliotfowler/Code/Libraries/Player/Player.xcworkspace -scheme Player -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build
```

The error reported from this is:
```
~/Library/Developer/Xcode/DerivedData/Player-aixpathpuwzwtebtpryxlkfzvjxs/Build/Intermediates/Player.build/Release-iphoneos/Player.build/unextended-module.modulemap:2:19: error: umbrella header 'Player.h' not found 
    umbrella header "Player.h"
```

After looking into it, I think it might be related to the fact that the umbrella file is named `Player.h` and the targets are named Player_iOS and Player_tvOS. According to [this StackOverflow answer](http://stackoverflow.com/a/39487620/809278) the umbrella file must share the name of the target. Unfortunately, that means we'll need 2 umbrella files for the 2 different targets.

### PR DESCRIPTION
**Pull request by eliotfowler**
This does 2 things to fix carthage installations:
- [x] Share the main Player scheme
- [x] Duplicate the Player.h umbrella file and rename each to match one of the targets

Closes #144

### CODE REVIEW

**Comment by eliotfowler** [comment]
Whew! Okay I think I finally got this working. I did end up having to re-arrange some things, but the good news is I think everything is working with Carthage.

**Comment by piemonte** [comment]
hey @eliotfowler thanks for the PR once again! you're awesome. it's quite a large footprint 👣 . i usually don't pull in changes where the commits aren't as atomic. i hope that's okay for now.

**Comment by eliotfowler** [comment]
Hey @piemonte, I totally understand. If you think this is a valuable feature add, I'm glad to take another stab at it while trying to minimize my changes. If not, no problem at all!

**Comment by piemonte** [comment]
@eliotfowler carthage support it is quite valuable! i'm sure folks who use it appreciate your contribution. 👍 

you'll have to forgive my turn around times, that's why the smaller commits and PRs are better.

**Pull request closed without merging**
