### PR TITLE
update path

### PR DESCRIPTION
**Pull request by pgherveou**
Not sure this how you planned to fix the bug that prevent user to load local video 
but I refactored the api to use a NSURL and this seems to work now for both remote and local files
Let me know what do you think

### CODE REVIEW

**Comment by pgherveou** [comment]
@piemonte any update? We are loading the pod from our branch now
but It would be nice to have a fix included in the official pod

**Comment by piemonte** [comment]
hey @pgherveou thanks for the contribution. @misslester or another will be able to merge it in and submit it for you. :v:

**Comment by pgherveou** [comment]
Cool Thanks @misslester let us know when you guys push it on cocoapods so we can give it a try!

**Comment by piemonte** [comment]
@pgherveou hey, looks like it was published when the merge was done:

https://github.com/piemonte/Player/releases/tag/0.0.8

**Pull request merged**
