### PR TITLE
Variable buffer size

### PR DESCRIPTION
**Pull request by karlisl**
Added "bufferSize" property.

### CODE REVIEW

**Comment by entotsu** [comment]
+1

**Comment by piemonte** [comment]
thanks @karlisl much appreciated ✌️ 

if you have some time to add this to the swift 3 branch too, that'd be awesome

**Comment by entotsu** [comment]
Oh... sorry...

 May be this is dangerous.... 😰 

For example,
when user paused by button, and then, may be video can restart to play by buffer. 😰 

So, I think that the control by buffer should be done by user of this Library.

This commit should revert... 🙏  😢

**Comment by karlisl** [comment]
@entotsu Player will restart video playback only when PlaybackState is "Playing". If video is manually paused by user, then it won't be restarted. 
Anyway, I will make changes so that by default "variable buffer size" option is turned off.

**Comment by entotsu** [comment]
oh! 😅 sorry...!

Thank you for your great PR! :relieved:

**Pull request merged**
