### PR TITLE
Add playerPlaybackDidLoop delegate method

### PR DESCRIPTION
**Pull request by qubblr**

### CODE REVIEW

**Comment by piemonte** [comment]
thanks @qubblr 🙌

**Comment by qubblr** [comment]
@piemonte Thanks for your prompt reply! Would you also mind to publish the updates to CocoaPods when you have a minute?

**Comment by piemonte** [comment]
will do this week 👍

**Comment by piemonte** [comment]
https://github.com/piemonte/Player/releases/tag/0.13.2

**Pull request merged**
