### PR TITLE
Swift2.0

### PR DESCRIPTION
**Pull request by lumenlunae**
The project was failing when I opened in Beta 4, this squashes the errors. :) Thank you!

### CODE REVIEW

**Comment by piemonte** [comment]
Hi @lumenlunae thanks for the contribution. Until Swift 2.0 comes out of beta, we have a Swift2.0 branch found here:

https://github.com/piemonte/Player/tree/swift2.0

Are you changes any different?

**Comment by lumenlunae** [comment]
Yes, even during beta swift changed, and your current branch showed a lot of compiler errors. The intention was just to bring it up to speed to the latest swift 2.0 version. :)

**Comment by piemonte** [comment]
ah @lumenlunae. apologies, i read your request too quickly. will make sure it gets taken care of.

**Comment by lumenlunae** [comment]
Thanks! :D

**Pull request merged**
